-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE POLICY users_update_message_deletes ON message_deletes FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
