-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS content_type TEXT NOT NULL DEFAULT 'text'; ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS media_url TEXT;
