-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS public.profiles (
 id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
 username TEXT UNIQUE,
 openid TEXT UNIQUE,
 unionid TEXT UNIQUE,
 nickname TEXT,
 avatar_url TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_select_profiles ON public.profiles
 FOR SELECT USING (true);

CREATE POLICY users_update_own_profile ON public.profiles
 FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

