-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE POLICY anon_select_chat_media ON storage.objects FOR SELECT USING (bucket_id = 'chat-media'); CREATE POLICY users_insert_chat_media ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'chat-media' AND auth.role() = 'authenticated');
