-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE POLICY users_update_read_at_messages ON public.messages
 FOR UPDATE USING (
 EXISTS (
 SELECT 1 FROM public.conversations c
 WHERE c.id = messages.conversation_id
 AND (c.user1_id = auth.uid() OR c.user2_id = auth.uid())
 )
 );
